### ISSUE TITLE
ecolab doesn't pick up system tcl

### ISSUE THREAD

**Issue by posix4e** [highperformancecoder/ecolab#1]
I tried to build ecolab and I get 

https://travis-ci.org/posix4e/ecolab/builds/102987845

I created a  vagrant just to be sure
vagrant@vagrant-ubuntu-trusty-64:~$ dpkg --list|grep tcl
ii  libtcl8.5:amd64                  8.5.15-2ubuntu1                     amd64        Tcl (the Tool Command Language) v8.5 - run-time library files
ii  tcl8.5                           8.5.15-2ubuntu1                     amd64        Tcl (the Tool Command Language) v8.5 - shell
ii  tcl8.5-dev:amd64                 8.5.15-2ubuntu1                     amd64        Tcl (the Tool Command Language) v8.5 - development files

Running make triggers
vagrant@vagrant-ubuntu-trusty-64:/vagrant/ecolab$ make 
include/Makefile:40: /vagrant/ecolab/include/Makefile.config: No such file or directory
Makefile:173: src/automorph.d: No such file or directory
Makefile:173: src/auxil.d: No such file or directory
Makefile:173: src/arrays.d: No such file or directory
Makefile:173: src/sparse_mat.d: No such file or directory
Makefile:173: src/findFirst.d: No such file or directory
Makefile:173: src/graph.d: No such file or directory
Makefile:173: src/netcomplexity.d: No such file or directory
Makefile:173: src/naugraph.d: No such file or directory
Makefile:173: src/nautil.d: No such file or directory
Makefile:173: src/nauty.d: No such file or directory
Makefile:173: src/nautinv.d: No such file or directory
Makefile:173: src/cachedDBM.d: No such file or directory
make: Warning: File `src/tclgraph.d' has modification time 1.2e+02 s in the future
g++ -fPIC -I. -I/vagrant/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/vagrant/ecolab/include -I/home/vagrant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DCONTIGUOUS -DECOLAB_LIB=\"/vagrant/ecolab/include\" -DNDEBUG -I/vagrant/ecolab/include -UECOLAB_LIB -DINSTALLED_ECOLAB_LIB=\"/home/vagrant/usr/ecolab/include\" -MM -MG src/cachedDBM.cc >src/cachedDBM.d
In file included from /vagrant/ecolab/include/cachedDBM.h:19:0,
                 from src/cachedDBM.cc:9:
/vagrant/ecolab/include/TCL_obj_base.h:81:2: error: #error TCL 8.x or greater supported. Please upgrade your TCL
 #error TCL 8.x or greater supported. Please upgrade your TCL
  ^
make: **\* [src/cachedDBM.d] Error 1

**Comment by highperformancecoder** [comment]
Are you trying to use Travis to build stuff? I only started working working with Travis last Thursday, and noticed it's Trusty Tahir build is not quite bog standard. Ecolab does builds correctly on Trusty Tahir, as does SciDAVis, the repo I was trying to Travis-enable last week. 

You will probably need to create you own TCL build and copy to your Travis VM - it was at the point of having to do this for some other package, that I called it a day.

**Comment by posix4e** [comment]
I am trying travis, but i'd be satisfied with doing it on a linux box. I have the results from the vagrant above? Perhaps the issue is you only support local installs of tcl and not package installs?

**Comment by posix4e** [comment]
The issue is that you don't pull in system tcl libs. -I /usr/include/tcl8.5

**Comment by posix4e** [comment]
If i move to apt-get install tcl/tk instead of tcl-8.5 it seems to fix it. https://travis-ci.org/posix4e/ecolab

**Comment by highperformancecoder** [comment]
Looks like you found the solution. Yes - I do support packaged installs on Ubuntu, even though Ubuntu (and Debian) install TCL/Tk in a weird place. However, as you note, specifying a version number to install puts TCL/Tk in an even weirder place. 

TCL/TK is now at version 8.7 I believe. I've certainly tested it against 8.6, and possibly 8.7 without noticing any problems.

**Comment by highperformancecoder** [comment]
If you want to hack the script in ECOLAB_HOME/include/Makefile to support all the possible weird and wonderful ways Debian/Ubuntu stashes their TCL, go ahead. It is not really a priority for me :(.

**Comment by posix4e** [comment]
Yea cleaning up travis and makefiles seems like a good place for me to add value without getting in the way of development. Crazy question,and I agnostic, is what we think about cmake?

**Comment by posix4e** [comment]
The new build gets a new error. https://travis-ci.org/posix4e/ecolab/builds/103007825 I'm going to close this and move forward.

**Comment by highperformancecoder** [comment]
I personally find Makefile generators more trouble than they're worth. But obviously I use them in other projects.

**Comment by posix4e** [comment]
Yea, I kinda agree. Here's the new  build https://travis-ci.org/posix4e/ecolab/builds/103008151

**Comment by highperformancecoder** [comment]
By that, I mean I'm constantly trying to second guess the Makefile generator by studying the generated Makefile, and then trying to guess what sort of changes to the input script is required to created the desired Makefile. I'd much rather just create the Makefile from scratch.

**Comment by highperformancecoder** [comment]
On Sun, Jan 17, 2016 at 03:36:40PM -0800, Alex Newman wrote:

> Yea, I kinda agree. Here's the new  build https://travis-ci.org/posix4e/ecolab/builds/103008151

You need to do "make sure" in your script to build and run the
regression tests. There will undoubtedly be extra dependencies
required to get it to work, though :).

Cheers

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by posix4e** [comment]
Sounds fun!

On Sun, Jan 17, 2016 at 3:44 PM Russell Standish notifications@github.com
wrote:

> On Sun, Jan 17, 2016 at 03:36:40PM -0800, Alex Newman wrote:
> 
> > Yea, I kinda agree. Here's the new build
> > https://travis-ci.org/posix4e/ecolab/builds/103008151
> 
> You need to do "make sure" in your script to build and run the
> regression tests. There will undoubtedly be extra dependencies
> required to get it to work, though :).
> 
> Cheers
> 
> ## 
> 
> ---
> 
> Dr Russell Standish Phone 0425 253119 (mobile)
> Principal, High Performance Coders
> Visiting Senior Research Fellow hpcoder@hpcoders.com.au
> Economics, Kingston University http://www.hpcoders.com.au
> 
> ---
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/highperformancecoder/ecolab/issues/1#issuecomment-172396147
> .
> 
> ## 

Sent from my mobile 5045076749
Alex Newman
