### ISSUE TITLE
Meson?

### ISSUE THREAD

**Issue by SolarAquarion** [highperformancecoder/ecolab#5]
Would it be possible for you to port the MAKEFILE to meson?

**Comment by highperformancecoder** [comment]
On Sun, Nov 26, 2017 at 01:04:17AM +0000, SolarAquarion wrote:
> Would it be possible for you to port the MAKEFILE to meson?
> 

What particular itch does Meson scratch?

Having experience of cmake, qmake, Visual Studio, hammer (a proprietry
scala-based build system at one company I worked for) and ant, I've
found that if you want to do something different to what the build
tool considered, it's tear your hair out time. In what way will Meson be a
different experience?


Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
It only requires python and since it just uses ninja it has simpler syntax

**Comment by highperformancecoder** [comment]
On Sun, Nov 26, 2017 at 01:25:27AM +0000, SolarAquarion wrote:
> It only requires python and since it just uses ninja it has simpler syntax

That reason was advanced in favour of all of the other build systems
mentioned. The trouble is, the behaviour of them tends to be
inscrutable (black box behaviour in the name of "user friendliness"),
which is a problem when (not if) you're trying to figure out why its
misbehaving.

Any particular reasons why Meson would be different?

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
The language that meson does stuff in is extremely readable and should
allow for easy debugging. But if the issue is the compiler then it's the
fault of ninja which is used by chromium. Meson is a configuration and
build system which is programmed in a way to avoid the problems of the past
like autotools and cmake

**Comment by highperformancecoder** [comment]
On Sun, Nov 26, 2017 at 02:10:38AM +0000, SolarAquarion wrote:
> The language that meson does stuff in is extremely readable and should
> allow for easy debugging. But if the issue is the compiler then it's the
> fault of ninja which is used by chromium. Meson is a configuration and
> build system which is programmed in a way to avoid the problems of the past
> like autotools and cmake
> 

I've been browsing the Meson docs, and I agree there's much to like. A
lot of what I lean on in GNU make is figuring out dependencies, and
providing ways of building different configurations. I see that
pkg-config is supported, but that will only be a subset of EcoLab's
dependencies. It will likely be a bit of a grind to figure out the
rest, though.

The other 2 necessary things I couldn't figure out from the Meson
manual:

1) Producing build dependency rules of C++ objects on header files
(such as gcc -MM -MG does for make).

2) Autogenerating classdesc generated output (.cd files)

I'm sure Meson authors have thought of this, but I couldn't see
obviously how to do it.

It'll be a big job, just for an evaluation, though. How do you propose
we start?

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
Begin with the easy stuff anything that is harder report to the meson issues

**Comment by SolarAquarion** [comment]
mingw is handled automatically, clean is handled automatically, Mac is
handled automatically, there are options for special cases for OS.

**Comment by SolarAquarion** [comment]
project('ecolab', 'c',
        version: '5.47',
          'c_std=gnu99',
        ],
        meson_version : '>= 0.42.1',
        license: 'MIT')

**Comment by highperformancecoder** [comment]
What about doing classdesc first? It's a much simpler project with far
fewer dependencies. And a prerequisite for EcoLab.

Cheers

On Sun, Nov 26, 2017 at 03:17:49AM +0000, SolarAquarion wrote:
> project('ecolab', 'c',
>         version: '5.47',
>           'c_std=gnu99',
>         ],
>         meson_version : '>= 0.42.1',
>         license: 'MIT')
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/ecolab/issues/5#issuecomment-346981103

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
Sounds good I suppose

**Comment by highperformancecoder** [comment]
I'm going to close this issue now. A parallel project was initiated to use meson with classdesc, but it ran aground of difficulties in using Meson - which seems a nice project, but not quite ready for prime time.
