### ISSUE TITLE
ecolab from opensuse apt repo doesn't install on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by wu-lee** [highperformancecoder/ecolab#6]
Hi,

I've managed to install and run Minsky without problems. Now I'm attempting to build Minsky. This appears to require ecolab.

I got a big clue on how to do this by reading the `.travis.yml` files in the minsky and ecolab source.

Firstly I tried building ecolab.  This failed, see a ticket to follow.

Then I noticed ecolab was in the opensuse apt repo referenced in the source, which I was able to add to my apt sources as part of the attempt to build ecolab:

    http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/

However, it appears to require a package libgsl0ldbl, which is not installable.  My attempt to install went like this:

```
  $ sudo apt install ecolab
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 ecolab : Depends: libgsl0ldbl (>= 1.9) but it is not installable
```

Also, I saw a suggestion that libgls2 is the current replacement:

```
  $ sudo apt install libgsl0ldbl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgsl0ldbl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgsl2 libgsl2:i386
```

I see when I check that libgsl2 is already installed.  Possibly this dependency needs to be updated?

**Comment by highperformancecoder** [comment]
This is what happens for me on Ubuntu 14.04:

root@ubuntu14045:~# apt install ecolab
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ecolab
0 to upgrade, 1 to newly install, 0 to remove and 171 not to upgrade.
Need to get 774 kB of archives.
After this operation, 6,077 kB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/  ecolab 5.50 [774 kB]
Fetched 774 kB in 7s (98.2 kB/s)                                               
Selecting previously unselected package ecolab.
(Reading database ... 131796 files and directories currently installed.)
Preparing to unpack .../archives/ecolab_5.50_amd64.deb ...
Unpacking ecolab (5.50) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up ecolab (5.50) ...

**Comment by highperformancecoder** [comment]
Did you set everything up as per https://software.opensuse.org//download.html?project=home%3Ahpcoder1&package=ecolab ?

**Comment by highperformancecoder** [comment]
My version is given by:
root@ubuntu14045:~# more /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by wu-lee** [comment]
I do believe I successfully set up the opensuse repository, as per the instructions you reference, which is essentially what the .travis.yml does.  I think if I hadn't the dependencies listed therein wouldn't install.

Can you tell me which version of libgsl you have installed there?   i.e. `dpkg -l 'libgsl*''  That might offer a clue to what the difference between our installs is with respect to this dependency.

**Comment by highperformancecoder** [comment]
~~~~
rks@ubuntu14045:~$ dpkg -l 'libgsl*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  libgsl0        <none>       <none>       (no description available)
ii  libgsl0-dev    1.16+dfsg-1u amd64        GNU Scientific Library (GSL) -- d
ii  libgsl0ldbl    1.16+dfsg-1u amd64        GNU Scientific Library (GSL) -- l
rks@ubuntu14045:~$ 
~~~~
