### ISSUE TITLE
build issues on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by wu-lee** [highperformancecoder/ecolab#7]
Hi - 

I'm attempting to build minsky; ecolab from your opensuse apt repository wont install (see #6).

As I mention there, I got a big clue on how to do this by reading the .travis.yml files in the ecolab source. Essentially I follow the steps:

  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/ /' >/tmp/hpcoders.list 
  - sudo mv /tmp/hpcoders.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - ./build_and_install_deps.sh
  - make AEGIS=1

At this point I discovered some missing dependencies, which I installed:
- libgmp-dev
- libgdbm-dev

Next came a problem with a missing linker symbol, `Db::open`.  I'll attach the full output from make, but the relevant part is:

```
g++ -O3 -Werror -Wall -Wno-unused-variable -fPIC -I. -I/data/nick/i/gitworking/misc/ecolab/test/../include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/data/nick/i/gitworking/misc/ecolab/test/../include -I/home/nick/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DUNURAN -DPRNG -DZLIB -DXDR_PACK -DIGRAPH -DCAIRO -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -DCONTIGUOUS -DTK -I/usr/include/tcl8.6 -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/data/nick/i/gitworking/misc/ecolab/test/../include\" -DNDEBUG -I/data/nick/i/gitworking/misc/ecolab/test/../include -DPANGO -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -g -UNDEBUG testCacheDBM.o /data/nick/i/gitworking/misc/ecolab/test/../lib/tclmain.o -u ecolab_tcl_arrays_link -u ecolab_tclgraph_link -u ecolab_analysis_link -u ecolab_random_link -u ecolab_cairo_types_link -u ecolab_plot_link -L/data/nick/i/gitworking/misc/ecolab/test/../lib -lecolab -ldl -L/data/nick/i/gitworking/misc/ecolab/test/../lib -L/home/nick/usr/lib -L/usr/local/lib -L/opt/local/lib -L/usr/X11R6/lib  -lunuran -lprng -lz -ligraph -lgmp -lcairo -ltk8.6 -ltkstub8.6 -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ltclstub8.6 -lX11 -lXss -lXext -lXft -lfontconfig -lfreetype -lfontconfig -lpthread -ldl -lz -lpthread -lieee -lm  -lm -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lcairo -o testCacheDBM
testCacheDBM.o: In function `Db::Db(char const*, Db::rw)':

/data/nick/i/gitworking/misc/ecolab/test/../include/cachedDBM.h:76: undefined reference to `Db::open(char const*, Db::rw)'
```
Following this are missing references to the other members of the Db class.  `git grep` tells me the methods are implemented in `src/cachedDBM.cc`, however I don't fully understand the linking method used, there is a comment about using the -u flag and catering for MacOS XCode. I wasn't able to fix this properly, but by modifying `test/Makefile` to omit the `testCacheDBM` and `testNDBM` targets from `MODELS` and `SPECIALS` respectively, the project finally built successfully.

If you could suggest the best way to fix the linkage problems, I can try and test that, then submit a patch.

Thanks.

**Comment by wu-lee** [comment]
[FAILURE.txt](https://github.com/highperformancecoder/ecolab/files/1638909/FAILURE.txt)
Make output attached.

One more thing I should also mention: although the compilation then succeeds, the resulting binary `bin/ecolab` fails:

```
  $ bin/ecolab 
terminate called after throwing an instance of 'ecolab::error'
  what():  cli->invalid command name "savebgerror"savebgerror->invalid command name "savebgerror"
```

**Comment by highperformancecoder** [comment]
The build and install deps script was designed for the Travis image. I think some packages come preinstalled, that are not there with a bare-bones install.

Re missing libdb support, you can disable that feature by specifying BDB= on the make command line. It is not needed for Minsky. Sometimes distros have db.h lying around, but the library is in an unusual place, in which case EcoLab tries to enable that feature, but fails to find the library.

Re /usr/bin/ecolab - it runs properly on my OpenSUSE box, but I get an error about a missing dynamic library on Ubuntu:

rks@ubuntu14045:~$ /usr/bin/ecolab 
/usr/bin/ecolab: error while loading shared libraries: libecolab.so.5.50: cannot open shared object file: No such file or directory

The binary is not really a target for the OBS packages, which are all about supporting downloadable minsky packages. But if you want to suggest improvements to the debian scripts at https://build.opensuse.org/package/show/home:hpcoder1/ecolab, please do so.

**Comment by wu-lee** [comment]
Just to be clear, the linkage problem seems to be a missing symbol from the ecolab project itself, not from *DBM, which I installed.  This symbol appears to be defined in cachedDBM.cc, just the object file containing it seems to be missing from the  linker invocation.

I shall also try building without DBM.

**Comment by highperformancecoder** [comment]
The only way that Db::open cannot be defined is if neither the macro BDB nor USE_DBM is defined. These are defined if the Makefile variables BDB and GDBM is defined respectively.

make BDB= GDBM= 
succeeds on my instance of Ubuntu 14.04.
