### ISSUE TITLE
build issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by danielhoey** [highperformancecoder/ecolab#8]
The build fails to find TCL on Ubuntu 18.04. The location of tclConfig.sh is /usr/lib/i386-linux-gnu/tcl8.5/ which is not in any of the search paths. I think the easiest solution is to check for it and link tclConfig.sh to a more standard location.This code in include/Makefile solves the problem

```
ifneq ($(call search,lib/*/tcl*/tclConfig.sh),)
  $(shell ln -s $(call search,lib/*/tcl*/tclConfig.sh) $(ECOLAB_HOME)/lib/tclConfig.sh)
endif
```
Apologies for not opening a pull request etc, didn't seem worth the effort for such a small change, but will do if you would prefer.

**Comment by highperformancecoder** [comment]
The puzzle is that ecolab builds just fine on Ubuntu 18.04 without
having to do this: see
https://build.opensuse.org/package/live_build_log/home:hpcoder1/ecolab/xUbuntu_18.04/x86_64

Is it possible that you didn't install the correct TCL package? I'm
using tcl-dev and tk-dev. TCL 8.5 seems a little old these days.

On Tue, Apr 16, 2019 at 04:06:01AM -0700, Daniel Hoey wrote:
> The build fails to find TCL on Ubuntu 18.04. The location of tclConfig.sh is /
> usr/lib/tcl8.5/ which is not in any of the search paths. I think the easiest
> solution is to check for it and copy tclConfig.sh into a more standard
> location. I've added this code to include/Makefile for this purpose:
> 
> ifneq ($(call search,lib/tcl*/tclConfig.sh),)
>   $(shell ln -s $(call search,lib/tcl*/tclConfig.sh) $(ECOLAB_HOME)/lib/tclConfig.sh)
> endif
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by danielhoey** [comment]
OK thanks. I replaced 8.5 with 8.6 and it built fine out of the box
