### ISSUE TITLE
link error for TCL_symbols not found

### ISSUE THREAD

**Issue by zhangzhao515** [highperformancecoder/ecolab#9]
I am trying to build ecolab-5.72 on my Mac pro (MacOS High Sierra 10.13.6). However it can't find Tcl APIs as follows.
Undefined symbols for architecture x86_64:
  "_Tcl_AppendResult", referenced from:
      int ecolab::exec_cmd<char const**>(ecolab::cmd_data*, Tcl_Interp*, int, char const**) in libecolab.a(TCL_obj.o)
      int ecolab::exec_cmd<Tcl_Obj* const*>(ecolab::cmd_data*, Tcl_Interp*, int, Tcl_Obj* const*) in libecolab.a(TCL_obj.o)
  "_Tcl_Close", referenced from:
      classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
      close_socket(int) in libecolab.a(TCL_obj.o)
      dumpdata(void*, Tcl_Channel_*, char*, int) in libecolab.a(TCL_obj.o)
  "_Tcl_CreateCommand", referenced from:
      ecolab::tclpp_cd::tclpp_cd(char const*, int, void (*)(int, char const**)) in tclmain.o
      ecolab::tclpp_cd::tclpp_cd(char const*, int, void (*)(int, char const**)) in libecolab.a(TCL_obj.o)
  "_Tcl_CreateExitHandler", referenced from:
      _main in tclmain.o
      ecolab::tclvar::operator=(char const*) in tclmain.o
      trap::sighand(int) in tclmain.o
      cli(int, char const**) in tclmain.o
      string_map(int, char const**) in tclmain.o
      string_is(int, char const**) in tclmain.o
      ecolab::tclpp_cd::tclpp_cd(char const*, int, void (*)(int, char const**)) in tclmain.o
      ...
  "_Tcl_CreateInterp", referenced from:
      _main in tclmain.o
      ecolab::tclvar::operator=(char const*) in tclmain.o
      trap::sighand(int) in tclmain.o
      cli(int, char const**) in tclmain.o
      string_map(int, char const**) in tclmain.o
      string_is(int, char const**) in tclmain.o
      ecolab::tclpp_cd::tclpp_cd(char const*, int, void (*)(int, char const**)) in tclmain.o
      ...
  "_Tcl_DeleteCommand", referenced from:
      ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libecolab.a(TCL_obj.o)
  "_Tcl_DoOneEvent", referenced from:
      int ecolab::exec_cmd<char const**>(ecolab::cmd_data*, Tcl_Interp*, int, char const**) in libecolab.a(TCL_obj.o)
      int ecolab::exec_cmd<Tcl_Obj* const*>(ecolab::cmd_data*, Tcl_Interp*, int, Tcl_Obj* const*) in libecolab.a(TCL_obj.o)
  "_Tcl_Eval", referenced from:
      trap::sighand(int) in tclmain.o
      ecolab::tclcmd::exec() in tclmain.o
      ecolab::tclcmd::exec() in libecolab.a(TCL_obj.o)
  "_Tcl_EvalFile", referenced from:
      _main in tclmain.o
  "_Tcl_ExprBoolean", referenced from:
      string_is(int, char const**) in tclmain.o
  "_Tcl_ExprDouble", referenced from:
      string_is(int, char const**) in tclmain.o
  "_Tcl_ExprLong", referenced from:
      string_is(int, char const**) in tclmain.o
  "_Tcl_FindExecutable", referenced from:
      _main in tclmain.o
  "_Tcl_Free", referenced from:
      string_map(int, char const**) in tclmain.o
      ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libecolab.a(TCL_obj.o)
  "_Tcl_GetString", referenced from:
      ecolab::TCL_args::str() in libecolab.a(TCL_obj.o)
  "_Tcl_GetStringResult", referenced from:
      _main in tclmain.o
      ecolab::tclcmd::exec() in tclmain.o
      ecolab::tclcmd::exec() in libecolab.a(TCL_obj.o)
  "_Tcl_GetVar", referenced from:
      _main in tclmain.o
      cli(int, char const**) in tclmain.o
  "_Tcl_Init", referenced from:
      _main in tclmain.o
  "_Tcl_OpenTcpClient", referenced from:
      classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
  "_Tcl_OpenTcpServer", referenced from:
      classdesc::TCL_obj_t::data_server(int, char**) in libecolab.a(TCL_obj.o)
  "_Tcl_Read", referenced from:
      classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
  "_Tcl_SetChannelOption", referenced from:
      classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
      dumpdata(void*, Tcl_Channel_*, char*, int) in libecolab.a(TCL_obj.o)
  "_Tcl_SetResult", referenced from:
      ecolab::tclreturn::~tclreturn() in tclmain.o
      ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libecolab.a(TCL_obj.o)
  "_Tcl_SetVar", referenced from:
      ecolab::tclvar::operator=(char const*) in tclmain.o
      ecolab::tclvar::dput(double) in tclmain.o
      ecolab::setEcoLabLib(char const*) in libecolab.a(TCL_obj.o)
      ecolab::tclvar::dput(double) in libecolab.a(TCL_obj.o)
  "_Tcl_SplitList", referenced from:
      string_map(int, char const**) in tclmain.o
      ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libecolab.a(TCL_obj.o)
  "_Tcl_Write", referenced from:
      dumpdata(void*, Tcl_Channel_*, char*, int) in libecolab.a(TCL_obj.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have build tcl from source (version 8.6.10) and set the path of tclConfig.sh in Makefile (I think) 
$(shell /Library/Frameworks/Tcl.framework/Versions/8.6/tclConfig.sh)
please help,
thank you.

**Comment by highperformancecoder** [comment]
It sounds to me that the Makefile is not finding the path to libtcl.dylib.

Have a look at the compile line that make outputs, and check that an
appropriate -L flag is set.

Personally, I use MacPorts for building all this stuff...

Cheers

On Mon, Jan 27, 2020 at 11:03:31PM -0800, zhangzhao515 wrote:
> I am trying to build ecolab-5.72 on my Mac pro (MacOS High Sierra 10.13.6).
> However it can't find Tcl APIs as follows.
> Undefined symbols for architecture x86_64:
> "_Tcl_AppendResult", referenced from:
> int ecolab::exec_cmd<char const**>(ecolab::cmd_data*, Tcl_Interp*, int, char
> const**) in libecolab.a(TCL_obj.o)
> int ecolab::exec_cmd<Tcl_Obj* const*>(ecolab::cmd_data*, Tcl_Interp*, int,
> Tcl_Obj* const*) in libecolab.a(TCL_obj.o)
> "Tcl_Close", referenced from:
> classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
> close_socket(int) in libecolab.a(TCL_obj.o)
> dumpdata(void*, Tcl_Channel, char, int) in libecolab.a(TCL_obj.o)
> "_Tcl_CreateCommand", referenced from:
> ecolab::tclpp_cd::tclpp_cd(char const*, int, void ()(int, char const**)) in
> tclmain.o
> ecolab::tclpp_cd::tclpp_cd(char const, int, void ()(int, char const**)) in
> libecolab.a(TCL_obj.o)
> "_Tcl_CreateExitHandler", referenced from:
> _main in tclmain.o
> ecolab::tclvar::operator=(char const) in tclmain.o
> trap::sighand(int) in tclmain.o
> cli(int, char const**) in tclmain.o
> string_map(int, char const**) in tclmain.o
> string_is(int, char const**) in tclmain.o
> ecolab::tclpp_cd::tclpp_cd(char const*, int, void ()(int, char const**)) in
> tclmain.o
> ...
> "_Tcl_CreateInterp", referenced from:
> _main in tclmain.o
> ecolab::tclvar::operator=(char const) in tclmain.o
> trap::sighand(int) in tclmain.o
> cli(int, char const**) in tclmain.o
> string_map(int, char const**) in tclmain.o
> string_is(int, char const**) in tclmain.o
> ecolab::tclpp_cd::tclpp_cd(char const*, int, void ()(int, char const**)) in
> tclmain.o
> ...
> "_Tcl_DeleteCommand", referenced from:
> ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits,
> std::__1::allocator > const&) in libecolab.a(TCL_obj.o)
> "_Tcl_DoOneEvent", referenced from:
> int ecolab::exec_cmd<char const**>(ecolab::cmd_data, Tcl_Interp*, int, char
> const**) in libecolab.a(TCL_obj.o)
> int ecolab::exec_cmd<Tcl_Obj* const*>(ecolab::cmd_data*, Tcl_Interp*, int,
> Tcl_Obj* const*) in libecolab.a(TCL_obj.o)
> "_Tcl_Eval", referenced from:
> trap::sighand(int) in tclmain.o
> ecolab::tclcmd::exec() in tclmain.o
> ecolab::tclcmd::exec() in libecolab.a(TCL_obj.o)
> "_Tcl_EvalFile", referenced from:
> _main in tclmain.o
> "_Tcl_ExprBoolean", referenced from:
> string_is(int, char const**) in tclmain.o
> "_Tcl_ExprDouble", referenced from:
> string_is(int, char const**) in tclmain.o
> "_Tcl_ExprLong", referenced from:
> string_is(int, char const**) in tclmain.o
> "_Tcl_FindExecutable", referenced from:
> _main in tclmain.o
> "_Tcl_Free", referenced from:
> string_map(int, char const**) in tclmain.o
> ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits,
> std::__1::allocator > const&) in libecolab.a(TCL_obj.o)
> "_Tcl_GetString", referenced from:
> ecolab::TCL_args::str() in libecolab.a(TCL_obj.o)
> "_Tcl_GetStringResult", referenced from:
> _main in tclmain.o
> ecolab::tclcmd::exec() in tclmain.o
> ecolab::tclcmd::exec() in libecolab.a(TCL_obj.o)
> "_Tcl_GetVar", referenced from:
> _main in tclmain.o
> cli(int, char const**) in tclmain.o
> "_Tcl_Init", referenced from:
> _main in tclmain.o
> "_Tcl_OpenTcpClient", referenced from:
> classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
> "_Tcl_OpenTcpServer", referenced from:
> classdesc::TCL_obj_t::data_server(int, char**) in libecolab.a(TCL_obj.o)
> "_Tcl_Read", referenced from:
> classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
> "Tcl_SetChannelOption", referenced from:
> classdesc::TCL_obj_t::get_vars(int, char**) in libecolab.a(TCL_obj.o)
> dumpdata(void*, Tcl_Channel, char, int) in libecolab.a(TCL_obj.o)
> "_Tcl_SetResult", referenced from:
> ecolab::tclreturn::~tclreturn() in tclmain.o
> ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits,
> std::__1::allocator > const&) in libecolab.a(TCL_obj.o)
> "_Tcl_SetVar", referenced from:
> ecolab::tclvar::operator=(char const*) in tclmain.o
> ecolab::tclvar::dput(double) in tclmain.o
> ecolab::setEcoLabLib(char const*) in libecolab.a(TCL_obj.o)
> ecolab::tclvar::dput(double) in libecolab.a(TCL_obj.o)
> "_Tcl_SplitList", referenced from:
> string_map(int, char const**) in tclmain.o
> ecolab::TCL_obj_deregister(std::__1::basic_string<char, std::__1::char_traits,
> std::__1::allocator > const&) in libecolab.a(TCL_obj.o)
> "Tcl_Write", referenced from:
> dumpdata(void*, Tcl_Channel, char, int) in libecolab.a(TCL_obj.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> I have build tcl from source (version 8.6.10) and set the path of tclConfig.sh
> in Makefile (I think)
> $(shell /Library/Frameworks/Tcl.framework/Versions/8.6/tclConfig.sh)
> please help,
> thank you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by zhangzhao515** [comment]
I am trying to locate that dynamic library on my laptop. But how can I tell the make to find libtcl.dylib? Thank you very much.

**Comment by zhangzhao515** [comment]
"sudo port install tcl" solve this problem. But I come to another link error:
Undefined symbols for architecture x86_64:
  "_ecolab_cairo_types_link", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
Maybe I am very close to the final success.
Thank you so much.
